Feat/adding mobula env
blockscout/docs-archive pull request #269
Opened 2024-04-28 19:05 UTC by xyeuu

- Adding mobula env

2024-06-03 12:08 UTC, vbaranov requested changes

2024-06-03 12:08 UTC, vbaranov commented on for-developers/information-and-settings/env-variables.md
> +| Variable                                             | Required | Description
The upstream branch has a new column `|Application |`. Your changes remove that column. Could you please pull updates from the master branch?

2024-06-03 12:09 UTC, sl1depengwyn requested changes

2024-06-03 12:09 UTC, sl1depengwyn commented on for-developers/information-and-settings/env-variables.md
> +| `EXCHANGE_RATES_MOBULA_COIN_ID`                      |          | Explicitly set Mobula coin ID.
Version for newly created envs should be `master`

2024-06-05 13:23 UTC, xyeuu commented on for-developers/information-and-settings/env-variables.md
> +| `EXCHANGE_RATES_MOBULA_COIN_ID`                      |          | Explicitly set Mobula coin ID.
What is the master version ? How do I find it ? Thanks

2024-06-05 18:38 UTC, sl1depengwyn commented on for-developers/information-and-settings/env-variables.md
> +| `EXCHANGE_RATES_MOBULA_COIN_ID`                      |          | Explicitly set Mobula coin ID.
You need to put `master` in the version field

2024-06-07 12:48 UTC, vbaranov approved these changes

2024-06-07 13:31 UTC, merged